// Generated by jextract

package dev.newty.mcpixel.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * int (*_CoreCrtSecureSearchSortCompareFunction)(void*,void*,void*);
 * }
 */
public interface _CoreCrtSecureSearchSortCompareFunction {

    int apply(java.lang.foreign.MemorySegment _x0, java.lang.foreign.MemorySegment _x1, java.lang.foreign.MemorySegment _x2);
    static MemorySegment allocate(_CoreCrtSecureSearchSortCompareFunction fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$9.const$1, fi, constants$9.const$0, scope);
    }
    static _CoreCrtSecureSearchSortCompareFunction ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment __x0, java.lang.foreign.MemorySegment __x1, java.lang.foreign.MemorySegment __x2) -> {
            try {
                return (int)constants$9.const$2.invokeExact(symbol, __x0, __x1, __x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


