// Generated by jextract

package dev.newty.mcpixel.ffi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "onexit",
        constants$23.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "hello_world",
        constants$0.const$2
    );
    static final MemorySegment const$2 = MemorySegment.ofAddress(0L);
    static final MemorySegment const$3 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("C");
}


